# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ljw-zlg/work/ZioTestApp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ljw-zlg/work/ZioTestApp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ljw-zlg/work/ZioTestApp/CMakeFiles /home/ljw-zlg/work/ZioTestApp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ljw-zlg/work/ZioTestApp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jsmn_wrapper

# Build rule for target.
jsmn_wrapper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jsmn_wrapper
.PHONY : jsmn_wrapper

# fast build rule for target.
jsmn_wrapper/fast:
	$(MAKE) -f 3rd/jsmn/CMakeFiles/jsmn_wrapper.dir/build.make 3rd/jsmn/CMakeFiles/jsmn_wrapper.dir/build
.PHONY : jsmn_wrapper/fast

#=============================================================================
# Target rules for targets named jsmn

# Build rule for target.
jsmn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jsmn
.PHONY : jsmn

# fast build rule for target.
jsmn/fast:
	$(MAKE) -f 3rd/jsmn/CMakeFiles/jsmn.dir/build.make 3rd/jsmn/CMakeFiles/jsmn.dir/build
.PHONY : jsmn/fast

#=============================================================================
# Target rules for targets named http_auth

# Build rule for target.
http_auth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_auth
.PHONY : http_auth

# fast build rule for target.
http_auth/fast:
	$(MAKE) -f zws_sdk/network/CMakeFiles/http_auth.dir/build.make zws_sdk/network/CMakeFiles/http_auth.dir/build
.PHONY : http_auth/fast

#=============================================================================
# Target rules for targets named http_download

# Build rule for target.
http_download: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_download
.PHONY : http_download

# fast build rule for target.
http_download/fast:
	$(MAKE) -f zws_sdk/network/CMakeFiles/http_download.dir/build.make zws_sdk/network/CMakeFiles/http_download.dir/build
.PHONY : http_download/fast

#=============================================================================
# Target rules for targets named mqtt_demo

# Build rule for target.
mqtt_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mqtt_demo
.PHONY : mqtt_demo

# fast build rule for target.
mqtt_demo/fast:
	$(MAKE) -f zws_sdk/network/CMakeFiles/mqtt_demo.dir/build.make zws_sdk/network/CMakeFiles/mqtt_demo.dir/build
.PHONY : mqtt_demo/fast

#=============================================================================
# Target rules for targets named echoc

# Build rule for target.
echoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echoc
.PHONY : echoc

# fast build rule for target.
echoc/fast:
	$(MAKE) -f zws_sdk/network/CMakeFiles/echoc.dir/build.make zws_sdk/network/CMakeFiles/echoc.dir/build
.PHONY : echoc/fast

#=============================================================================
# Target rules for targets named network

# Build rule for target.
network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 network
.PHONY : network

# fast build rule for target.
network/fast:
	$(MAKE) -f zws_sdk/network/CMakeFiles/network.dir/build.make zws_sdk/network/CMakeFiles/network.dir/build
.PHONY : network/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f zws_sdk/protocol/common/CMakeFiles/client.dir/build.make zws_sdk/protocol/common/CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named app_pugrade

# Build rule for target.
app_pugrade: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app_pugrade
.PHONY : app_pugrade

# fast build rule for target.
app_pugrade/fast:
	$(MAKE) -f app/upgrade/CMakeFiles/app_pugrade.dir/build.make app/upgrade/CMakeFiles/app_pugrade.dir/build
.PHONY : app_pugrade/fast

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) -f app/utils/CMakeFiles/utils.dir/build.make app/utils/CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named ecat_master

# Build rule for target.
ecat_master: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ecat_master
.PHONY : ecat_master

# fast build rule for target.
ecat_master/fast:
	$(MAKE) -f app/ecat_master/CMakeFiles/ecat_master.dir/build.make app/ecat_master/CMakeFiles/ecat_master.dir/build
.PHONY : ecat_master/fast

#=============================================================================
# Target rules for targets named app_test

# Build rule for target.
app_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app_test
.PHONY : app_test

# fast build rule for target.
app_test/fast:
	$(MAKE) -f app/application/CMakeFiles/app_test.dir/build.make app/application/CMakeFiles/app_test.dir/build
.PHONY : app_test/fast

#=============================================================================
# Target rules for targets named MasterOfZio

# Build rule for target.
MasterOfZio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MasterOfZio
.PHONY : MasterOfZio

# fast build rule for target.
MasterOfZio/fast:
	$(MAKE) -f app/application/CMakeFiles/MasterOfZio.dir/build.make app/application/CMakeFiles/MasterOfZio.dir/build
.PHONY : MasterOfZio/fast

#=============================================================================
# Target rules for targets named database

# Build rule for target.
database: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 database
.PHONY : database

# fast build rule for target.
database/fast:
	$(MAKE) -f app/database/CMakeFiles/database.dir/build.make app/database/CMakeFiles/database.dir/build
.PHONY : database/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... jsmn_wrapper"
	@echo "... jsmn"
	@echo "... http_auth"
	@echo "... http_download"
	@echo "... mqtt_demo"
	@echo "... echoc"
	@echo "... network"
	@echo "... client"
	@echo "... app_pugrade"
	@echo "... utils"
	@echo "... ecat_master"
	@echo "... app_test"
	@echo "... MasterOfZio"
	@echo "... database"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

